### ISSUE TITLE
Android Build Problem

### ISSUE THREAD

**Issue by hetunandu** [ppsreejith/react-native-paytm#2]
I have followed the android setup guide as on the readme

When building the debug apk i get the following error

`/Users/hetu/code/Projects/Noted/Noted/node_modules/react-native-paytm/android/src/main/java/com/reactlibrary/RNPayTmModule.java:13: error: invalid method declaration; return type required
  public RNShareModule(ReactApplicationContext reactContext) {`

I know it says that build  tested on iOS only but any way this can be figured out?

React Native version 0.39

**Comment by sam17** [comment]
@ppsreejith Do you plan to test it on android on anytime soon?

**Comment by ppsreejith** [comment]
Hey, I've updated the readme. See if this works.
